### ISSUE TITLE
Check if homepage

### ISSUE THREAD

**Issue by akhil99** [shovikguha/MVRT_Site#6]
Currently, in app/js/main.js, there is a line:
```
if(!isHomePage)...
```
and `isHomePage` is set to ` $('.home')`

However, `if(isHomepage)` seems to always return `true`, even when the current page isn't the homepage.

Is this intended?

**Comment by trotod** [comment]
I think I may have overcomplicated the JS there, but the idea is that if the page isn't a homepage, then nothing should happen. `isHomePage` should be false unless if the page has a `home` class on the body element.

Wrapping everything in IIFEs may not be the best idea though...

**Comment by akhil99** [comment]
I tried it out. If the current page has nothing with the class `.home`, it
returns `[]`. When I tried it in the console, and in the code, `if( [] )`
evaluates to true. Instead, you should evaluate `$('.home').length == 0`

**Comment by akhil99** [comment]
I tried it out. If the current page has nothing with the class `.home`, it
returns `[]`. When I tried it in the console, and in the code, `if( [] )`
evaluates to true. Instead, you should evaluate `$('.home').length == 0`

**Comment by trotod** [comment]
Technically it returns an array-like object, but you are right, `!!$('.home') === true`. But I feel like the JS file is pretty messed up, (and I really feel like using [browserify][0] as well as switching to [gulp][1]), so we should wait. But if you want to fix it your self go ahead.

**Comment by trotod** [comment]
fixed at commit 49d82cb
